cpp-omnet-mode

(ev "EV << \"" (p "string") "\"" q ";")
(emt "emit(" (p "signal_id") ", " (p "long") ");")
(intuni "intuniform(" (p "0") ", " (p "1") ")")
(inccmath "#include <cmath>")
(nanchk "isnan(" (p "x") ")")
(incomnet "#include <omnetpp.h>")
(prm (p "var") " = par(\"" (p "par") "\");")
(sched "scheduleAt(simTime()+" (p "1.0") ", " (p "event") ");")
(uni "uniform(" (p "0") ", " (p "1") ")")
